### ISSUE TITLE
Could you please add odoo 11

### ISSUE THREAD

**Issue by zachary** [cloudflavor/odoo-k8s#1]
Could you please add odoo 11?

thanks

**Comment by PI-Victor** [comment]
@zachary sorry for the late reply. will update right away and test :)

**Comment by PI-Victor** [comment]
<img width="176" alt="screen shot 2018-03-25 at 21 08 32" src="https://user-images.githubusercontent.com/6294120/37879537-cc58f622-307a-11e8-95cb-56cdf87c130c.png">

All of the examples have been updated to odoo 11.
Closing this as resolved.
